#!/bin/sh

set -x


apt-get install -y \
    isolinux \
    syslinux-common \
    dosfstools
export PATH=$PATH:/sbin
which mkdosfs
echo $PATH
dpkg -L dosfstools
mkdir -p /usr/lib/syslinux
cp /usr/lib/ISOLINUX/isolinux.bin /usr/lib/syslinux/isolinux.bin
cp /usr/lib/shim/shimx64.efi.signed /usr/lib/shim/shim.efi.signed
cp /usr/lib/syslinux/modules/bios/ldlinux.c32 /usr/lib/syslinux