#!/bin/bash

# MIT License
#
# Copyright (c) 2017 Leo (중광) Przybylski 

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


mkdir -p /opt/miners /opt/bin 

# Ethminer
mkdir -p /tmp/build-ethminer
cd /tmp/build-ethminer
curl -OL https://github.com/ethereum-mining/ethminer/releases/download/v0.12.0/ethminer-0.12.0-Linux.tar.gz
tar -xzvf ethminer-0.12.0-Linux.tar.gz
mv bin/* /opt/bin

cat > /etc/systemd/system/ethminer.service <<EOF
[Unit]
Description=Ethminer Service
Requires=network.target
After=multi-user.target
[Service]
Type=simple
WorkingDirectory=/
PermissionsStartOnly=true
ExecStart=/opt/bin/ethminer --farm-recheck 10000 -S eth-us-west1.nanopool.org:9999 -G -O 0x44F78cb91936926c8b55D76442cDdD7981DB7254.miner2/r351574nc3@gmail.com:x   
ExecReload=/bin/kill -HUP
ExecStop=/bin/kill -15
Restart=on-failure
StandardOutput=journal
StandardError=journal
[Install]
WantedBy=multi-user.target
EOF

systemctl enable ethminer
cd -
rm -rf /tmp/build-ethminer