#!/bin/bash

# MIT License
#
# Copyright (c) 2017 Leo (중광) Przybylski 

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

export PATH=$PATH:/sbin

#apt-get install -y 
#    curl \
#    bzip2

mkdir -p /tmp/build
#cd /tmp/build \
#    && curl -OL http://repo.radeon.com/rocm/archive/apt_1.6.4.tar.bz2 \
#    && tar -xjf apt_1.6.4.tar.bz2 

#cat /tmp/build/apt_1.6.4/rocm.gpg.key | sudo apt-key add -
#echo deb file:///tmp/build/apt_1.6.4 xenial main > /etc/apt/sources.list.d/rocm.list

#apt-get update

# Install new 4.11.0-kfd-compute-rocm-rel-1.6-180 Kernel
#apt-get install -y --allow-unauthenticated rocm

#AMDGPU_DRIVER_VERSION=16.60-379184
AMDGPU_DRIVER_VERSION=17.50-511655

#rm -rf /tmp/build

# Download drivers
#cd /tmp/build \
#    && curl -OL https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-${AMDGPU_DRIVER_VERSION}.tar.xz -e http://support.amd.com \
#    && tar -xJvf amdgpu-pro-${AMDGPU_DRIVER_VERSION}.tar.xz \
#    && cd amdgpu-pro-${AMDGPU_DRIVER_VERSION} \
#    && ./amdgpu-pro-install  -y 

#apt-get -y install clinfo-amdgpu-pro
#echo 'export LLVM_BIN=/opt/amdgpu-pro/bin' | sudo tee /etc/profile.d/amdgpu-pro.sh

#apt-get install -y compute-firmware
wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | apt-key add -
sh -c 'echo deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'
apt-get update
apt-get install -y rocm-dkms rocm-opencl

#cat /var/lib/dkms/rock/1.7.60-ubuntu/build/make.log
